# Generated by Django 4.0.1 on 2022-01-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_loginuser_email_alter_loginuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='birth_date',
            new_name='birth_day',
        ),
    ]
